// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-dialog-1": () => import("@/registry-reui/bases/radix/components/dialog/c-dialog-1.tsx"),
  "c-dialog-2": () => import("@/registry-reui/bases/radix/components/dialog/c-dialog-2.tsx"),
  "c-dialog-3": () => import("@/registry-reui/bases/radix/components/dialog/c-dialog-3.tsx"),
  "c-dialog-4": () => import("@/registry-reui/bases/radix/components/dialog/c-dialog-4.tsx"),
  "c-dialog-5": () => import("@/registry-reui/bases/radix/components/dialog/c-dialog-5.tsx"),
  "c-dialog-6": () => import("@/registry-reui/bases/radix/components/dialog/c-dialog-6.tsx"),
  "c-dialog-7": () => import("@/registry-reui/bases/radix/components/dialog/c-dialog-7.tsx"),
  "c-dialog-8": () => import("@/registry-reui/bases/radix/components/dialog/c-dialog-8.tsx"),
  "c-dialog-9": () => import("@/registry-reui/bases/radix/components/dialog/c-dialog-9.tsx"),
  "c-dialog-10": () => import("@/registry-reui/bases/radix/components/dialog/c-dialog-10.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
