// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-native-select-1": () => import("@/registry-reui/bases/radix/components/native-select/c-native-select-1.tsx"),
  "c-native-select-2": () => import("@/registry-reui/bases/radix/components/native-select/c-native-select-2.tsx"),
  "c-native-select-3": () => import("@/registry-reui/bases/radix/components/native-select/c-native-select-3.tsx"),
  "c-native-select-4": () => import("@/registry-reui/bases/radix/components/native-select/c-native-select-4.tsx"),
  "c-native-select-5": () => import("@/registry-reui/bases/radix/components/native-select/c-native-select-5.tsx"),
  "c-native-select-6": () => import("@/registry-reui/bases/radix/components/native-select/c-native-select-6.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
