// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-tooltip-1": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-1.tsx"),
  "c-tooltip-2": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-2.tsx"),
  "c-tooltip-3": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-3.tsx"),
  "c-tooltip-4": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-4.tsx"),
  "c-tooltip-5": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-5.tsx"),
  "c-tooltip-6": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-6.tsx"),
  "c-tooltip-7": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-7.tsx"),
  "c-tooltip-8": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-8.tsx"),
  "c-tooltip-9": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-9.tsx"),
  "c-tooltip-10": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-10.tsx"),
  "c-tooltip-11": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-11.tsx"),
  "c-tooltip-12": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-12.tsx"),
  "c-tooltip-13": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-13.tsx"),
  "c-tooltip-14": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-14.tsx"),
  "c-tooltip-15": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-15.tsx"),
  "c-tooltip-16": () => import("@/registry-reui/bases/radix/components/tooltip/c-tooltip-16.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
