// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-radio-group-1": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-1.tsx"),
  "c-radio-group-2": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-2.tsx"),
  "c-radio-group-3": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-3.tsx"),
  "c-radio-group-4": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-4.tsx"),
  "c-radio-group-5": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-5.tsx"),
  "c-radio-group-6": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-6.tsx"),
  "c-radio-group-7": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-7.tsx"),
  "c-radio-group-8": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-8.tsx"),
  "c-radio-group-9": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-9.tsx"),
  "c-radio-group-10": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-10.tsx"),
  "c-radio-group-11": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-11.tsx"),
  "c-radio-group-12": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-12.tsx"),
  "c-radio-group-13": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-13.tsx"),
  "c-radio-group-14": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-14.tsx"),
  "c-radio-group-15": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-15.tsx"),
  "c-radio-group-16": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-16.tsx"),
  "c-radio-group-17": () => import("@/registry-reui/bases/base/components/radio-group/c-radio-group-17.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
