// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-table-1": () => import("@/registry-reui/bases/radix/components/table/c-table-1.tsx"),
  "c-table-2": () => import("@/registry-reui/bases/radix/components/table/c-table-2.tsx"),
  "c-table-3": () => import("@/registry-reui/bases/radix/components/table/c-table-3.tsx"),
  "c-table-4": () => import("@/registry-reui/bases/radix/components/table/c-table-4.tsx"),
  "c-table-5": () => import("@/registry-reui/bases/radix/components/table/c-table-5.tsx"),
  "c-table-6": () => import("@/registry-reui/bases/radix/components/table/c-table-6.tsx"),
  "c-table-7": () => import("@/registry-reui/bases/radix/components/table/c-table-7.tsx"),
  "c-table-8": () => import("@/registry-reui/bases/radix/components/table/c-table-8.tsx"),
  "c-table-9": () => import("@/registry-reui/bases/radix/components/table/c-table-9.tsx"),
  "c-table-10": () => import("@/registry-reui/bases/radix/components/table/c-table-10.tsx"),
  "c-table-11": () => import("@/registry-reui/bases/radix/components/table/c-table-11.tsx"),
  "c-table-12": () => import("@/registry-reui/bases/radix/components/table/c-table-12.tsx"),
  "c-table-13": () => import("@/registry-reui/bases/radix/components/table/c-table-13.tsx"),
  "c-table-14": () => import("@/registry-reui/bases/radix/components/table/c-table-14.tsx"),
  "c-table-15": () => import("@/registry-reui/bases/radix/components/table/c-table-15.tsx"),
  "c-table-16": () => import("@/registry-reui/bases/radix/components/table/c-table-16.tsx"),
  "c-table-17": () => import("@/registry-reui/bases/radix/components/table/c-table-17.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
