// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-sonner-1": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-1.tsx"),
  "c-sonner-2": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-2.tsx"),
  "c-sonner-3": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-3.tsx"),
  "c-sonner-4": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-4.tsx"),
  "c-sonner-5": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-5.tsx"),
  "c-sonner-6": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-6.tsx"),
  "c-sonner-7": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-7.tsx"),
  "c-sonner-8": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-8.tsx"),
  "c-sonner-9": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-9.tsx"),
  "c-sonner-10": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-10.tsx"),
  "c-sonner-11": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-11.tsx"),
  "c-sonner-12": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-12.tsx"),
  "c-sonner-13": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-13.tsx"),
  "c-sonner-14": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-14.tsx"),
  "c-sonner-15": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-15.tsx"),
  "c-sonner-16": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-16.tsx"),
  "c-sonner-17": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-17.tsx"),
  "c-sonner-18": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-18.tsx"),
  "c-sonner-19": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-19.tsx"),
  "c-sonner-20": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-20.tsx"),
  "c-sonner-21": () => import("@/registry-reui/bases/radix/components/sonner/c-sonner-21.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
