// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-kbd-1": () => import("@/registry-reui/bases/radix/components/kbd/c-kbd-1.tsx"),
  "c-kbd-2": () => import("@/registry-reui/bases/radix/components/kbd/c-kbd-2.tsx"),
  "c-kbd-3": () => import("@/registry-reui/bases/radix/components/kbd/c-kbd-3.tsx"),
  "c-kbd-4": () => import("@/registry-reui/bases/radix/components/kbd/c-kbd-4.tsx"),
  "c-kbd-5": () => import("@/registry-reui/bases/radix/components/kbd/c-kbd-5.tsx"),
  "c-kbd-6": () => import("@/registry-reui/bases/radix/components/kbd/c-kbd-6.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
