// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-chart-1": () => import("@/registry-reui/bases/base/components/chart/c-chart-1.tsx"),
  "c-chart-2": () => import("@/registry-reui/bases/base/components/chart/c-chart-2.tsx"),
  "c-chart-3": () => import("@/registry-reui/bases/base/components/chart/c-chart-3.tsx"),
  "c-chart-4": () => import("@/registry-reui/bases/base/components/chart/c-chart-4.tsx"),
  "c-chart-5": () => import("@/registry-reui/bases/base/components/chart/c-chart-5.tsx"),
  "c-chart-6": () => import("@/registry-reui/bases/base/components/chart/c-chart-6.tsx"),
  "c-chart-7": () => import("@/registry-reui/bases/base/components/chart/c-chart-7.tsx"),
  "c-chart-8": () => import("@/registry-reui/bases/base/components/chart/c-chart-8.tsx"),
  "c-chart-9": () => import("@/registry-reui/bases/base/components/chart/c-chart-9.tsx"),
  "c-chart-10": () => import("@/registry-reui/bases/base/components/chart/c-chart-10.tsx"),
  "c-chart-11": () => import("@/registry-reui/bases/base/components/chart/c-chart-11.tsx"),
  "c-chart-12": () => import("@/registry-reui/bases/base/components/chart/c-chart-12.tsx"),
  "c-chart-13": () => import("@/registry-reui/bases/base/components/chart/c-chart-13.tsx"),
  "c-chart-14": () => import("@/registry-reui/bases/base/components/chart/c-chart-14.tsx"),
  "c-chart-15": () => import("@/registry-reui/bases/base/components/chart/c-chart-15.tsx"),
  "c-chart-16": () => import("@/registry-reui/bases/base/components/chart/c-chart-16.tsx"),
  "c-chart-17": () => import("@/registry-reui/bases/base/components/chart/c-chart-17.tsx"),
  "c-chart-18": () => import("@/registry-reui/bases/base/components/chart/c-chart-18.tsx"),
  "c-chart-19": () => import("@/registry-reui/bases/base/components/chart/c-chart-19.tsx"),
  "c-chart-20": () => import("@/registry-reui/bases/base/components/chart/c-chart-20.tsx"),
  "c-chart-21": () => import("@/registry-reui/bases/base/components/chart/c-chart-21.tsx"),
  "c-chart-22": () => import("@/registry-reui/bases/base/components/chart/c-chart-22.tsx"),
  "c-chart-23": () => import("@/registry-reui/bases/base/components/chart/c-chart-23.tsx"),
  "c-chart-24": () => import("@/registry-reui/bases/base/components/chart/c-chart-24.tsx"),
  "c-chart-25": () => import("@/registry-reui/bases/base/components/chart/c-chart-25.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
