// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-file-upload-1": () => import("@/registry-reui/bases/base/components/file-upload/c-file-upload-1.tsx"),
  "c-file-upload-2": () => import("@/registry-reui/bases/base/components/file-upload/c-file-upload-2.tsx"),
  "c-file-upload-3": () => import("@/registry-reui/bases/base/components/file-upload/c-file-upload-3.tsx"),
  "c-file-upload-4": () => import("@/registry-reui/bases/base/components/file-upload/c-file-upload-4.tsx"),
  "c-file-upload-5": () => import("@/registry-reui/bases/base/components/file-upload/c-file-upload-5.tsx"),
  "c-file-upload-6": () => import("@/registry-reui/bases/base/components/file-upload/c-file-upload-6.tsx"),
  "c-file-upload-7": () => import("@/registry-reui/bases/base/components/file-upload/c-file-upload-7.tsx"),
  "c-file-upload-8": () => import("@/registry-reui/bases/base/components/file-upload/c-file-upload-8.tsx"),
  "c-file-upload-9": () => import("@/registry-reui/bases/base/components/file-upload/c-file-upload-9.tsx"),
  "c-file-upload-10": () => import("@/registry-reui/bases/base/components/file-upload/c-file-upload-10.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
