// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-scrollspy-1": () => import("@/registry-reui/bases/base/components/scrollspy/c-scrollspy-1.tsx"),
  "c-scrollspy-2": () => import("@/registry-reui/bases/base/components/scrollspy/c-scrollspy-2.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
