// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-skeleton-1": () => import("@/registry-reui/bases/radix/components/skeleton/c-skeleton-1.tsx"),
  "c-skeleton-2": () => import("@/registry-reui/bases/radix/components/skeleton/c-skeleton-2.tsx"),
  "c-skeleton-3": () => import("@/registry-reui/bases/radix/components/skeleton/c-skeleton-3.tsx"),
  "c-skeleton-4": () => import("@/registry-reui/bases/radix/components/skeleton/c-skeleton-4.tsx"),
  "c-skeleton-5": () => import("@/registry-reui/bases/radix/components/skeleton/c-skeleton-5.tsx"),
  "c-skeleton-6": () => import("@/registry-reui/bases/radix/components/skeleton/c-skeleton-6.tsx"),
  "c-skeleton-7": () => import("@/registry-reui/bases/radix/components/skeleton/c-skeleton-7.tsx"),
  "c-skeleton-8": () => import("@/registry-reui/bases/radix/components/skeleton/c-skeleton-8.tsx"),
  "c-skeleton-9": () => import("@/registry-reui/bases/radix/components/skeleton/c-skeleton-9.tsx"),
  "c-skeleton-10": () => import("@/registry-reui/bases/radix/components/skeleton/c-skeleton-10.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
