// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-number-field-1": () => import("@/registry-reui/bases/base/components/number-field/c-number-field-1.tsx"),
  "c-number-field-2": () => import("@/registry-reui/bases/base/components/number-field/c-number-field-2.tsx"),
  "c-number-field-3": () => import("@/registry-reui/bases/base/components/number-field/c-number-field-3.tsx"),
  "c-number-field-4": () => import("@/registry-reui/bases/base/components/number-field/c-number-field-4.tsx"),
  "c-number-field-5": () => import("@/registry-reui/bases/base/components/number-field/c-number-field-5.tsx"),
  "c-number-field-6": () => import("@/registry-reui/bases/base/components/number-field/c-number-field-6.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
