// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-checkbox-1": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-1.tsx"),
  "c-checkbox-2": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-2.tsx"),
  "c-checkbox-3": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-3.tsx"),
  "c-checkbox-4": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-4.tsx"),
  "c-checkbox-5": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-5.tsx"),
  "c-checkbox-6": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-6.tsx"),
  "c-checkbox-7": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-7.tsx"),
  "c-checkbox-8": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-8.tsx"),
  "c-checkbox-9": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-9.tsx"),
  "c-checkbox-10": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-10.tsx"),
  "c-checkbox-11": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-11.tsx"),
  "c-checkbox-12": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-12.tsx"),
  "c-checkbox-13": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-13.tsx"),
  "c-checkbox-14": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-14.tsx"),
  "c-checkbox-15": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-15.tsx"),
  "c-checkbox-16": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-16.tsx"),
  "c-checkbox-17": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-17.tsx"),
  "c-checkbox-18": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-18.tsx"),
  "c-checkbox-19": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-19.tsx"),
  "c-checkbox-20": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-20.tsx"),
  "c-checkbox-21": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-21.tsx"),
  "c-checkbox-22": () => import("@/registry-reui/bases/radix/components/checkbox/c-checkbox-22.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
