// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-field-1": () => import("@/registry-reui/bases/base/components/field/c-field-1.tsx"),
  "c-field-2": () => import("@/registry-reui/bases/base/components/field/c-field-2.tsx"),
  "c-field-3": () => import("@/registry-reui/bases/base/components/field/c-field-3.tsx"),
  "c-field-4": () => import("@/registry-reui/bases/base/components/field/c-field-4.tsx"),
  "c-field-5": () => import("@/registry-reui/bases/base/components/field/c-field-5.tsx"),
  "c-field-6": () => import("@/registry-reui/bases/base/components/field/c-field-6.tsx"),
  "c-field-7": () => import("@/registry-reui/bases/base/components/field/c-field-7.tsx"),
  "c-field-8": () => import("@/registry-reui/bases/base/components/field/c-field-8.tsx"),
  "c-field-9": () => import("@/registry-reui/bases/base/components/field/c-field-9.tsx"),
  "c-field-10": () => import("@/registry-reui/bases/base/components/field/c-field-10.tsx"),
  "c-field-11": () => import("@/registry-reui/bases/base/components/field/c-field-11.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
