// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-calendar-1": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-1.tsx"),
  "c-calendar-2": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-2.tsx"),
  "c-calendar-3": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-3.tsx"),
  "c-calendar-4": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-4.tsx"),
  "c-calendar-5": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-5.tsx"),
  "c-calendar-6": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-6.tsx"),
  "c-calendar-7": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-7.tsx"),
  "c-calendar-8": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-8.tsx"),
  "c-calendar-9": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-9.tsx"),
  "c-calendar-10": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-10.tsx"),
  "c-calendar-11": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-11.tsx"),
  "c-calendar-12": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-12.tsx"),
  "c-calendar-13": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-13.tsx"),
  "c-calendar-14": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-14.tsx"),
  "c-calendar-15": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-15.tsx"),
  "c-calendar-16": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-16.tsx"),
  "c-calendar-17": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-17.tsx"),
  "c-calendar-18": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-18.tsx"),
  "c-calendar-19": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-19.tsx"),
  "c-calendar-20": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-20.tsx"),
  "c-calendar-21": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-21.tsx"),
  "c-calendar-22": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-22.tsx"),
  "c-calendar-23": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-23.tsx"),
  "c-calendar-24": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-24.tsx"),
  "c-calendar-25": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-25.tsx"),
  "c-calendar-26": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-26.tsx"),
  "c-calendar-27": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-27.tsx"),
  "c-calendar-28": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-28.tsx"),
  "c-calendar-29": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-29.tsx"),
  "c-calendar-30": () => import("@/registry-reui/bases/radix/components/calendar/c-calendar-30.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
