// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-code-block-1": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-1.tsx"),
  "c-code-block-2": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-2.tsx"),
  "c-code-block-3": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-3.tsx"),
  "c-code-block-4": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-4.tsx"),
  "c-code-block-5": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-5.tsx"),
  "c-code-block-6": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-6.tsx"),
  "c-code-block-7": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-7.tsx"),
  "c-code-block-8": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-8.tsx"),
  "c-code-block-9": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-9.tsx"),
  "c-code-block-10": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-10.tsx"),
  "c-code-block-11": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-11.tsx"),
  "c-code-block-12": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-12.tsx"),
  "c-code-block-13": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-13.tsx"),
  "c-code-block-14": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-14.tsx"),
  "c-code-block-15": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-15.tsx"),
  "c-code-block-16": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-16.tsx"),
  "c-code-block-17": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-17.tsx"),
  "c-code-block-18": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-18.tsx"),
  "c-code-block-19": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-19.tsx"),
  "c-code-block-20": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-20.tsx"),
  "c-code-block-21": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-21.tsx"),
  "c-code-block-22": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-22.tsx"),
  "c-code-block-23": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-23.tsx"),
  "c-code-block-24": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-24.tsx"),
  "c-code-block-25": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-25.tsx"),
  "c-code-block-26": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-26.tsx"),
  "c-code-block-27": () => import("@/registry-reui/bases/base/components/code-block/c-code-block-27.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
