// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-timeline-1": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-1.tsx"),
  "c-timeline-2": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-2.tsx"),
  "c-timeline-3": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-3.tsx"),
  "c-timeline-4": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-4.tsx"),
  "c-timeline-5": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-5.tsx"),
  "c-timeline-6": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-6.tsx"),
  "c-timeline-7": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-7.tsx"),
  "c-timeline-8": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-8.tsx"),
  "c-timeline-9": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-9.tsx"),
  "c-timeline-10": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-10.tsx"),
  "c-timeline-11": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-11.tsx"),
  "c-timeline-12": () => import("@/registry-reui/bases/radix/components/timeline/c-timeline-12.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
