// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-filters-1": () => import("@/registry-reui/bases/base/components/filters/c-filters-1.tsx"),
  "c-filters-2": () => import("@/registry-reui/bases/base/components/filters/c-filters-2.tsx"),
  "c-filters-3": () => import("@/registry-reui/bases/base/components/filters/c-filters-3.tsx"),
  "c-filters-4": () => import("@/registry-reui/bases/base/components/filters/c-filters-4.tsx"),
  "c-filters-5": () => import("@/registry-reui/bases/base/components/filters/c-filters-5.tsx"),
  "c-filters-6": () => import("@/registry-reui/bases/base/components/filters/c-filters-6.tsx"),
  "c-filters-7": () => import("@/registry-reui/bases/base/components/filters/c-filters-7.tsx"),
  "c-filters-8": () => import("@/registry-reui/bases/base/components/filters/c-filters-8.tsx"),
  "c-filters-9": () => import("@/registry-reui/bases/base/components/filters/c-filters-9.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
