// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-icon-stack-1": () => import("@/registry-reui/bases/base/components/icon-stack/c-icon-stack-1.tsx"),
  "c-icon-stack-2": () => import("@/registry-reui/bases/base/components/icon-stack/c-icon-stack-2.tsx"),
  "c-icon-stack-3": () => import("@/registry-reui/bases/base/components/icon-stack/c-icon-stack-3.tsx"),
  "c-icon-stack-4": () => import("@/registry-reui/bases/base/components/icon-stack/c-icon-stack-4.tsx"),
  "c-icon-stack-5": () => import("@/registry-reui/bases/base/components/icon-stack/c-icon-stack-5.tsx"),
  "c-icon-stack-6": () => import("@/registry-reui/bases/base/components/icon-stack/c-icon-stack-6.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
