// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-gantt-1": () => import("@/registry-reui/bases/radix/components/gantt/c-gantt-1.tsx"),
  "c-gantt-2": () => import("@/registry-reui/bases/radix/components/gantt/c-gantt-2.tsx"),
  "c-gantt-3": () => import("@/registry-reui/bases/radix/components/gantt/c-gantt-3.tsx"),
  "c-gantt-4": () => import("@/registry-reui/bases/radix/components/gantt/c-gantt-4.tsx"),
  "c-gantt-5": () => import("@/registry-reui/bases/radix/components/gantt/c-gantt-5.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
