// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-dropdown-menu-1": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-1.tsx"),
  "c-dropdown-menu-2": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-2.tsx"),
  "c-dropdown-menu-3": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-3.tsx"),
  "c-dropdown-menu-4": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-4.tsx"),
  "c-dropdown-menu-5": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-5.tsx"),
  "c-dropdown-menu-6": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-6.tsx"),
  "c-dropdown-menu-7": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-7.tsx"),
  "c-dropdown-menu-8": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-8.tsx"),
  "c-dropdown-menu-9": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-9.tsx"),
  "c-dropdown-menu-10": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-10.tsx"),
  "c-dropdown-menu-11": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-11.tsx"),
  "c-dropdown-menu-12": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-12.tsx"),
  "c-dropdown-menu-13": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-13.tsx"),
  "c-dropdown-menu-14": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-14.tsx"),
  "c-dropdown-menu-15": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-15.tsx"),
  "c-dropdown-menu-16": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-16.tsx"),
  "c-dropdown-menu-17": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-17.tsx"),
  "c-dropdown-menu-18": () => import("@/registry-reui/bases/base/components/dropdown-menu/c-dropdown-menu-18.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
