// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-autocomplete-1": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-1.tsx"),
  "c-autocomplete-2": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-2.tsx"),
  "c-autocomplete-3": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-3.tsx"),
  "c-autocomplete-4": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-4.tsx"),
  "c-autocomplete-5": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-5.tsx"),
  "c-autocomplete-6": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-6.tsx"),
  "c-autocomplete-7": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-7.tsx"),
  "c-autocomplete-8": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-8.tsx"),
  "c-autocomplete-9": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-9.tsx"),
  "c-autocomplete-10": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-10.tsx"),
  "c-autocomplete-11": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-11.tsx"),
  "c-autocomplete-12": () => import("@/registry-reui/bases/radix/components/autocomplete/c-autocomplete-12.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
