// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-input-1": () => import("@/registry-reui/bases/base/components/input/c-input-1.tsx"),
  "c-input-2": () => import("@/registry-reui/bases/base/components/input/c-input-2.tsx"),
  "c-input-3": () => import("@/registry-reui/bases/base/components/input/c-input-3.tsx"),
  "c-input-4": () => import("@/registry-reui/bases/base/components/input/c-input-4.tsx"),
  "c-input-5": () => import("@/registry-reui/bases/base/components/input/c-input-5.tsx"),
  "c-input-6": () => import("@/registry-reui/bases/base/components/input/c-input-6.tsx"),
  "c-input-7": () => import("@/registry-reui/bases/base/components/input/c-input-7.tsx"),
  "c-input-8": () => import("@/registry-reui/bases/base/components/input/c-input-8.tsx"),
  "c-input-9": () => import("@/registry-reui/bases/base/components/input/c-input-9.tsx"),
  "c-input-10": () => import("@/registry-reui/bases/base/components/input/c-input-10.tsx"),
  "c-input-11": () => import("@/registry-reui/bases/base/components/input/c-input-11.tsx"),
  "c-input-12": () => import("@/registry-reui/bases/base/components/input/c-input-12.tsx"),
  "c-input-13": () => import("@/registry-reui/bases/base/components/input/c-input-13.tsx"),
  "c-input-14": () => import("@/registry-reui/bases/base/components/input/c-input-14.tsx"),
  "c-input-15": () => import("@/registry-reui/bases/base/components/input/c-input-15.tsx"),
  "c-input-16": () => import("@/registry-reui/bases/base/components/input/c-input-16.tsx"),
  "c-input-17": () => import("@/registry-reui/bases/base/components/input/c-input-17.tsx"),
  "c-input-18": () => import("@/registry-reui/bases/base/components/input/c-input-18.tsx"),
  "c-input-19": () => import("@/registry-reui/bases/base/components/input/c-input-19.tsx"),
  "c-input-20": () => import("@/registry-reui/bases/base/components/input/c-input-20.tsx"),
  "c-input-21": () => import("@/registry-reui/bases/base/components/input/c-input-21.tsx"),
  "c-input-22": () => import("@/registry-reui/bases/base/components/input/c-input-22.tsx"),
  "c-input-23": () => import("@/registry-reui/bases/base/components/input/c-input-23.tsx"),
  "c-input-24": () => import("@/registry-reui/bases/base/components/input/c-input-24.tsx"),
  "c-input-25": () => import("@/registry-reui/bases/base/components/input/c-input-25.tsx"),
  "c-input-26": () => import("@/registry-reui/bases/base/components/input/c-input-26.tsx"),
  "c-input-27": () => import("@/registry-reui/bases/base/components/input/c-input-27.tsx"),
  "c-input-28": () => import("@/registry-reui/bases/base/components/input/c-input-28.tsx"),
  "c-input-29": () => import("@/registry-reui/bases/base/components/input/c-input-29.tsx"),
  "c-input-30": () => import("@/registry-reui/bases/base/components/input/c-input-30.tsx"),
  "c-input-31": () => import("@/registry-reui/bases/base/components/input/c-input-31.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
