// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-rating-1": () => import("@/registry-reui/bases/base/components/rating/c-rating-1.tsx"),
  "c-rating-2": () => import("@/registry-reui/bases/base/components/rating/c-rating-2.tsx"),
  "c-rating-3": () => import("@/registry-reui/bases/base/components/rating/c-rating-3.tsx"),
  "c-rating-4": () => import("@/registry-reui/bases/base/components/rating/c-rating-4.tsx"),
  "c-rating-5": () => import("@/registry-reui/bases/base/components/rating/c-rating-5.tsx"),
  "c-rating-6": () => import("@/registry-reui/bases/base/components/rating/c-rating-6.tsx"),
  "c-rating-7": () => import("@/registry-reui/bases/base/components/rating/c-rating-7.tsx"),
  "c-rating-8": () => import("@/registry-reui/bases/base/components/rating/c-rating-8.tsx"),
  "c-rating-9": () => import("@/registry-reui/bases/base/components/rating/c-rating-9.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
