// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-aspect-ratio-1": () => import("@/registry-reui/bases/radix/components/aspect-ratio/c-aspect-ratio-1.tsx"),
  "c-aspect-ratio-2": () => import("@/registry-reui/bases/radix/components/aspect-ratio/c-aspect-ratio-2.tsx"),
  "c-aspect-ratio-3": () => import("@/registry-reui/bases/radix/components/aspect-ratio/c-aspect-ratio-3.tsx"),
  "c-aspect-ratio-4": () => import("@/registry-reui/bases/radix/components/aspect-ratio/c-aspect-ratio-4.tsx"),
  "c-aspect-ratio-5": () => import("@/registry-reui/bases/radix/components/aspect-ratio/c-aspect-ratio-5.tsx"),
  "c-aspect-ratio-6": () => import("@/registry-reui/bases/radix/components/aspect-ratio/c-aspect-ratio-6.tsx"),
  "c-aspect-ratio-7": () => import("@/registry-reui/bases/radix/components/aspect-ratio/c-aspect-ratio-7.tsx"),
  "c-aspect-ratio-8": () => import("@/registry-reui/bases/radix/components/aspect-ratio/c-aspect-ratio-8.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
