// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-alert-1": () => import("@/registry-reui/bases/base/components/alert/c-alert-1.tsx"),
  "c-alert-2": () => import("@/registry-reui/bases/base/components/alert/c-alert-2.tsx"),
  "c-alert-3": () => import("@/registry-reui/bases/base/components/alert/c-alert-3.tsx"),
  "c-alert-4": () => import("@/registry-reui/bases/base/components/alert/c-alert-4.tsx"),
  "c-alert-5": () => import("@/registry-reui/bases/base/components/alert/c-alert-5.tsx"),
  "c-alert-6": () => import("@/registry-reui/bases/base/components/alert/c-alert-6.tsx"),
  "c-alert-7": () => import("@/registry-reui/bases/base/components/alert/c-alert-7.tsx"),
  "c-alert-8": () => import("@/registry-reui/bases/base/components/alert/c-alert-8.tsx"),
  "c-alert-9": () => import("@/registry-reui/bases/base/components/alert/c-alert-9.tsx"),
  "c-alert-10": () => import("@/registry-reui/bases/base/components/alert/c-alert-10.tsx"),
  "c-alert-11": () => import("@/registry-reui/bases/base/components/alert/c-alert-11.tsx"),
  "c-alert-12": () => import("@/registry-reui/bases/base/components/alert/c-alert-12.tsx"),
  "c-alert-13": () => import("@/registry-reui/bases/base/components/alert/c-alert-13.tsx"),
  "c-alert-14": () => import("@/registry-reui/bases/base/components/alert/c-alert-14.tsx"),
  "c-alert-15": () => import("@/registry-reui/bases/base/components/alert/c-alert-15.tsx"),
  "c-alert-16": () => import("@/registry-reui/bases/base/components/alert/c-alert-16.tsx"),
  "c-alert-17": () => import("@/registry-reui/bases/base/components/alert/c-alert-17.tsx"),
  "c-alert-18": () => import("@/registry-reui/bases/base/components/alert/c-alert-18.tsx"),
  "c-alert-19": () => import("@/registry-reui/bases/base/components/alert/c-alert-19.tsx"),
  "c-alert-20": () => import("@/registry-reui/bases/base/components/alert/c-alert-20.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
