// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-card-1": () => import("@/registry-reui/bases/radix/components/card/c-card-1.tsx"),
  "c-card-2": () => import("@/registry-reui/bases/radix/components/card/c-card-2.tsx"),
  "c-card-3": () => import("@/registry-reui/bases/radix/components/card/c-card-3.tsx"),
  "c-card-4": () => import("@/registry-reui/bases/radix/components/card/c-card-4.tsx"),
  "c-card-5": () => import("@/registry-reui/bases/radix/components/card/c-card-5.tsx"),
  "c-card-6": () => import("@/registry-reui/bases/radix/components/card/c-card-6.tsx"),
  "c-card-7": () => import("@/registry-reui/bases/radix/components/card/c-card-7.tsx"),
  "c-card-8": () => import("@/registry-reui/bases/radix/components/card/c-card-8.tsx"),
  "c-card-9": () => import("@/registry-reui/bases/radix/components/card/c-card-9.tsx"),
  "c-card-10": () => import("@/registry-reui/bases/radix/components/card/c-card-10.tsx"),
  "c-card-11": () => import("@/registry-reui/bases/radix/components/card/c-card-11.tsx"),
  "c-card-12": () => import("@/registry-reui/bases/radix/components/card/c-card-12.tsx"),
  "c-card-13": () => import("@/registry-reui/bases/radix/components/card/c-card-13.tsx"),
  "c-card-14": () => import("@/registry-reui/bases/radix/components/card/c-card-14.tsx"),
  "c-card-15": () => import("@/registry-reui/bases/radix/components/card/c-card-15.tsx"),
  "c-card-16": () => import("@/registry-reui/bases/radix/components/card/c-card-16.tsx"),
  "c-card-17": () => import("@/registry-reui/bases/radix/components/card/c-card-17.tsx"),
  "c-card-18": () => import("@/registry-reui/bases/radix/components/card/c-card-18.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
