// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-item-1": () => import("@/registry-reui/bases/radix/components/item/c-item-1.tsx"),
  "c-item-2": () => import("@/registry-reui/bases/radix/components/item/c-item-2.tsx"),
  "c-item-3": () => import("@/registry-reui/bases/radix/components/item/c-item-3.tsx"),
  "c-item-4": () => import("@/registry-reui/bases/radix/components/item/c-item-4.tsx"),
  "c-item-5": () => import("@/registry-reui/bases/radix/components/item/c-item-5.tsx"),
  "c-item-6": () => import("@/registry-reui/bases/radix/components/item/c-item-6.tsx"),
  "c-item-7": () => import("@/registry-reui/bases/radix/components/item/c-item-7.tsx"),
  "c-item-8": () => import("@/registry-reui/bases/radix/components/item/c-item-8.tsx"),
  "c-item-9": () => import("@/registry-reui/bases/radix/components/item/c-item-9.tsx"),
  "c-item-10": () => import("@/registry-reui/bases/radix/components/item/c-item-10.tsx"),
  "c-item-11": () => import("@/registry-reui/bases/radix/components/item/c-item-11.tsx"),
  "c-item-12": () => import("@/registry-reui/bases/radix/components/item/c-item-12.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
