// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-badge-1": () => import("@/registry-reui/bases/base/components/badge/c-badge-1.tsx"),
  "c-badge-2": () => import("@/registry-reui/bases/base/components/badge/c-badge-2.tsx"),
  "c-badge-3": () => import("@/registry-reui/bases/base/components/badge/c-badge-3.tsx"),
  "c-badge-4": () => import("@/registry-reui/bases/base/components/badge/c-badge-4.tsx"),
  "c-badge-5": () => import("@/registry-reui/bases/base/components/badge/c-badge-5.tsx"),
  "c-badge-6": () => import("@/registry-reui/bases/base/components/badge/c-badge-6.tsx"),
  "c-badge-7": () => import("@/registry-reui/bases/base/components/badge/c-badge-7.tsx"),
  "c-badge-8": () => import("@/registry-reui/bases/base/components/badge/c-badge-8.tsx"),
  "c-badge-9": () => import("@/registry-reui/bases/base/components/badge/c-badge-9.tsx"),
  "c-badge-10": () => import("@/registry-reui/bases/base/components/badge/c-badge-10.tsx"),
  "c-badge-11": () => import("@/registry-reui/bases/base/components/badge/c-badge-11.tsx"),
  "c-badge-12": () => import("@/registry-reui/bases/base/components/badge/c-badge-12.tsx"),
  "c-badge-13": () => import("@/registry-reui/bases/base/components/badge/c-badge-13.tsx"),
  "c-badge-14": () => import("@/registry-reui/bases/base/components/badge/c-badge-14.tsx"),
  "c-badge-15": () => import("@/registry-reui/bases/base/components/badge/c-badge-15.tsx"),
  "c-badge-16": () => import("@/registry-reui/bases/base/components/badge/c-badge-16.tsx"),
  "c-badge-17": () => import("@/registry-reui/bases/base/components/badge/c-badge-17.tsx"),
  "c-badge-18": () => import("@/registry-reui/bases/base/components/badge/c-badge-18.tsx"),
  "c-badge-19": () => import("@/registry-reui/bases/base/components/badge/c-badge-19.tsx"),
  "c-badge-20": () => import("@/registry-reui/bases/base/components/badge/c-badge-20.tsx"),
  "c-badge-21": () => import("@/registry-reui/bases/base/components/badge/c-badge-21.tsx"),
  "c-badge-22": () => import("@/registry-reui/bases/base/components/badge/c-badge-22.tsx"),
  "c-badge-23": () => import("@/registry-reui/bases/base/components/badge/c-badge-23.tsx"),
  "c-badge-24": () => import("@/registry-reui/bases/base/components/badge/c-badge-24.tsx"),
  "c-badge-25": () => import("@/registry-reui/bases/base/components/badge/c-badge-25.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
