// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-accordion-1": () => import("@/registry-reui/bases/radix/components/accordion/c-accordion-1.tsx"),
  "c-accordion-2": () => import("@/registry-reui/bases/radix/components/accordion/c-accordion-2.tsx"),
  "c-accordion-3": () => import("@/registry-reui/bases/radix/components/accordion/c-accordion-3.tsx"),
  "c-accordion-4": () => import("@/registry-reui/bases/radix/components/accordion/c-accordion-4.tsx"),
  "c-accordion-5": () => import("@/registry-reui/bases/radix/components/accordion/c-accordion-5.tsx"),
  "c-accordion-6": () => import("@/registry-reui/bases/radix/components/accordion/c-accordion-6.tsx"),
  "c-accordion-7": () => import("@/registry-reui/bases/radix/components/accordion/c-accordion-7.tsx"),
  "c-accordion-8": () => import("@/registry-reui/bases/radix/components/accordion/c-accordion-8.tsx"),
  "c-accordion-9": () => import("@/registry-reui/bases/radix/components/accordion/c-accordion-9.tsx"),
  "c-accordion-10": () => import("@/registry-reui/bases/radix/components/accordion/c-accordion-10.tsx"),
  "c-accordion-11": () => import("@/registry-reui/bases/radix/components/accordion/c-accordion-11.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
