// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-frame-1": () => import("@/registry-reui/bases/radix/components/frame/c-frame-1.tsx"),
  "c-frame-2": () => import("@/registry-reui/bases/radix/components/frame/c-frame-2.tsx"),
  "c-frame-3": () => import("@/registry-reui/bases/radix/components/frame/c-frame-3.tsx"),
  "c-frame-4": () => import("@/registry-reui/bases/radix/components/frame/c-frame-4.tsx"),
  "c-frame-5": () => import("@/registry-reui/bases/radix/components/frame/c-frame-5.tsx"),
  "c-frame-6": () => import("@/registry-reui/bases/radix/components/frame/c-frame-6.tsx"),
  "c-frame-7": () => import("@/registry-reui/bases/radix/components/frame/c-frame-7.tsx"),
  "c-frame-8": () => import("@/registry-reui/bases/radix/components/frame/c-frame-8.tsx"),
  "c-frame-9": () => import("@/registry-reui/bases/radix/components/frame/c-frame-9.tsx"),
  "c-frame-10": () => import("@/registry-reui/bases/radix/components/frame/c-frame-10.tsx"),
  "c-frame-11": () => import("@/registry-reui/bases/radix/components/frame/c-frame-11.tsx"),
  "c-frame-12": () => import("@/registry-reui/bases/radix/components/frame/c-frame-12.tsx"),
  "c-frame-13": () => import("@/registry-reui/bases/radix/components/frame/c-frame-13.tsx"),
  "c-frame-14": () => import("@/registry-reui/bases/radix/components/frame/c-frame-14.tsx"),
  "c-frame-15": () => import("@/registry-reui/bases/radix/components/frame/c-frame-15.tsx"),
  "c-frame-16": () => import("@/registry-reui/bases/radix/components/frame/c-frame-16.tsx"),
  "c-frame-17": () => import("@/registry-reui/bases/radix/components/frame/c-frame-17.tsx"),
  "c-frame-18": () => import("@/registry-reui/bases/radix/components/frame/c-frame-18.tsx"),
  "c-frame-19": () => import("@/registry-reui/bases/radix/components/frame/c-frame-19.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
