// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-label-1": () => import("@/registry-reui/bases/base/components/label/c-label-1.tsx"),
  "c-label-2": () => import("@/registry-reui/bases/base/components/label/c-label-2.tsx"),
  "c-label-3": () => import("@/registry-reui/bases/base/components/label/c-label-3.tsx"),
  "c-label-4": () => import("@/registry-reui/bases/base/components/label/c-label-4.tsx"),
  "c-label-5": () => import("@/registry-reui/bases/base/components/label/c-label-5.tsx"),
  "c-label-6": () => import("@/registry-reui/bases/base/components/label/c-label-6.tsx"),
  "c-label-7": () => import("@/registry-reui/bases/base/components/label/c-label-7.tsx"),
  "c-label-8": () => import("@/registry-reui/bases/base/components/label/c-label-8.tsx"),
  "c-label-9": () => import("@/registry-reui/bases/base/components/label/c-label-9.tsx"),
  "c-label-10": () => import("@/registry-reui/bases/base/components/label/c-label-10.tsx"),
  "c-label-11": () => import("@/registry-reui/bases/base/components/label/c-label-11.tsx"),
  "c-label-12": () => import("@/registry-reui/bases/base/components/label/c-label-12.tsx"),
  "c-label-13": () => import("@/registry-reui/bases/base/components/label/c-label-13.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
