// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-sortable-1": () => import("@/registry-reui/bases/radix/components/sortable/c-sortable-1.tsx"),
  "c-sortable-2": () => import("@/registry-reui/bases/radix/components/sortable/c-sortable-2.tsx"),
  "c-sortable-3": () => import("@/registry-reui/bases/radix/components/sortable/c-sortable-3.tsx"),
  "c-sortable-4": () => import("@/registry-reui/bases/radix/components/sortable/c-sortable-4.tsx"),
  "c-sortable-5": () => import("@/registry-reui/bases/radix/components/sortable/c-sortable-5.tsx"),
  "c-sortable-6": () => import("@/registry-reui/bases/radix/components/sortable/c-sortable-6.tsx"),
  "c-sortable-7": () => import("@/registry-reui/bases/radix/components/sortable/c-sortable-7.tsx"),
  "c-sortable-8": () => import("@/registry-reui/bases/radix/components/sortable/c-sortable-8.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
