// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-toggle-1": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-1.tsx"),
  "c-toggle-2": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-2.tsx"),
  "c-toggle-3": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-3.tsx"),
  "c-toggle-4": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-4.tsx"),
  "c-toggle-5": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-5.tsx"),
  "c-toggle-6": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-6.tsx"),
  "c-toggle-7": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-7.tsx"),
  "c-toggle-8": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-8.tsx"),
  "c-toggle-9": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-9.tsx"),
  "c-toggle-10": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-10.tsx"),
  "c-toggle-11": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-11.tsx"),
  "c-toggle-12": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-12.tsx"),
  "c-toggle-13": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-13.tsx"),
  "c-toggle-14": () => import("@/registry-reui/bases/radix/components/toggle/c-toggle-14.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
