// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-alert-dialog-1": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-1.tsx"),
  "c-alert-dialog-2": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-2.tsx"),
  "c-alert-dialog-3": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-3.tsx"),
  "c-alert-dialog-4": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-4.tsx"),
  "c-alert-dialog-5": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-5.tsx"),
  "c-alert-dialog-6": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-6.tsx"),
  "c-alert-dialog-7": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-7.tsx"),
  "c-alert-dialog-8": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-8.tsx"),
  "c-alert-dialog-9": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-9.tsx"),
  "c-alert-dialog-10": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-10.tsx"),
  "c-alert-dialog-11": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-11.tsx"),
  "c-alert-dialog-12": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-12.tsx"),
  "c-alert-dialog-13": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-13.tsx"),
  "c-alert-dialog-14": () => import("@/registry-reui/bases/radix/components/alert-dialog/c-alert-dialog-14.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
