// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-stepper-1": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-1.tsx"),
  "c-stepper-2": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-2.tsx"),
  "c-stepper-3": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-3.tsx"),
  "c-stepper-4": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-4.tsx"),
  "c-stepper-5": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-5.tsx"),
  "c-stepper-6": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-6.tsx"),
  "c-stepper-7": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-7.tsx"),
  "c-stepper-8": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-8.tsx"),
  "c-stepper-9": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-9.tsx"),
  "c-stepper-10": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-10.tsx"),
  "c-stepper-11": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-11.tsx"),
  "c-stepper-12": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-12.tsx"),
  "c-stepper-13": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-13.tsx"),
  "c-stepper-14": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-14.tsx"),
  "c-stepper-15": () => import("@/registry-reui/bases/base/components/stepper/c-stepper-15.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
