// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-empty-1": () => import("@/registry-reui/bases/base/components/empty/c-empty-1.tsx"),
  "c-empty-2": () => import("@/registry-reui/bases/base/components/empty/c-empty-2.tsx"),
  "c-empty-3": () => import("@/registry-reui/bases/base/components/empty/c-empty-3.tsx"),
  "c-empty-4": () => import("@/registry-reui/bases/base/components/empty/c-empty-4.tsx"),
  "c-empty-5": () => import("@/registry-reui/bases/base/components/empty/c-empty-5.tsx"),
  "c-empty-6": () => import("@/registry-reui/bases/base/components/empty/c-empty-6.tsx"),
  "c-empty-7": () => import("@/registry-reui/bases/base/components/empty/c-empty-7.tsx"),
  "c-empty-8": () => import("@/registry-reui/bases/base/components/empty/c-empty-8.tsx"),
  "c-empty-9": () => import("@/registry-reui/bases/base/components/empty/c-empty-9.tsx"),
  "c-empty-10": () => import("@/registry-reui/bases/base/components/empty/c-empty-10.tsx"),
  "c-empty-11": () => import("@/registry-reui/bases/base/components/empty/c-empty-11.tsx"),
  "c-empty-12": () => import("@/registry-reui/bases/base/components/empty/c-empty-12.tsx"),
  "c-empty-13": () => import("@/registry-reui/bases/base/components/empty/c-empty-13.tsx"),
  "c-empty-14": () => import("@/registry-reui/bases/base/components/empty/c-empty-14.tsx"),
  "c-empty-15": () => import("@/registry-reui/bases/base/components/empty/c-empty-15.tsx"),
  "c-empty-16": () => import("@/registry-reui/bases/base/components/empty/c-empty-16.tsx"),
  "c-empty-17": () => import("@/registry-reui/bases/base/components/empty/c-empty-17.tsx"),
  "c-empty-18": () => import("@/registry-reui/bases/base/components/empty/c-empty-18.tsx"),
  "c-empty-19": () => import("@/registry-reui/bases/base/components/empty/c-empty-19.tsx"),
  "c-empty-20": () => import("@/registry-reui/bases/base/components/empty/c-empty-20.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
