// Generated by build-component-packages.mts. Do not edit by hand.
// Lazy-import map of every component preview in this category.

export const componentPreviewLoaders = {
  "c-kanban-1": () => import("@/registry-reui/bases/radix/components/kanban/c-kanban-1.tsx"),
  "c-kanban-2": () => import("@/registry-reui/bases/radix/components/kanban/c-kanban-2.tsx"),
  "c-kanban-3": () => import("@/registry-reui/bases/radix/components/kanban/c-kanban-3.tsx"),
  "c-kanban-4": () => import("@/registry-reui/bases/radix/components/kanban/c-kanban-4.tsx"),
  "c-kanban-5": () => import("@/registry-reui/bases/radix/components/kanban/c-kanban-5.tsx"),
} as const

export type ComponentName = keyof typeof componentPreviewLoaders
